CREATE DATABASE my;
use my;
CREATE TABLE PLAYERS(
id INT  auto_increment PRIMARY KEY,
playerName VARCHAR(50),
country VARCHAR(50),
points INT,
positions varchar(50),
basicprice INT
);
DROP TABLE PLAYERS;
SELECT * FROM PLAYERS;
SELECT * FROM PLAYERS WHERE ID = 4;

CREATE TABLE A1(
NUMBERS INT AUTO_INCREMENT PRIMARY KEY,
CSK INT,
RCB INT,
MI INT,
PASS VARCHAR(50),
BUDGET INT,
CONSTRAINT FK_PLAYERS_CSK FOREIGN KEY(CSK) REFERENCES PLAYERS(id),
CONSTRAINT FK_PLAYERS_RCB FOREIGN KEY(RCB) REFERENCES PLAYERS(id),
CONSTRAINT FK_PLAYERS_MI  FOREIGN KEY(MI)  REFERENCES PLAYERS(id)
);
DROP TABLE A1;
SELECT * FROM A1;
INSERT INTO A1(CSK,RCB,MI) VALUES (1,2,3),(3,2,1);

UPDATE a1 SET soldPlayers = 0 WHERE NUMBERS = 12;

SELECT teamName FROM A1 WHERE NUMBERS = 1;

SELECT PASS FROM A1 where teamName = 'MI';

SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'A1';
SELECT PASS FROM A1 WHERE NUMBERS = (13 - 2);

SHOW columns FROM A1;
select CSK FROM A1;

SELECT BUDGET FROM a1 WHERE teamName = 'srh';

SELECT * FROM A1 LIMIT 0;

SELECT * FROM A1
WHERE NUMBERS = 1;

UPDATE A1
SET PASS = "GOWTHAM"
WHERE NUMBERS = 1;

UPDATE A1 SET PASS = 'Gowtham' WHERE NUMBERS = 2;

INSERT INTO A1 (PASS) VALUES ('A1');

INSERT INTO PLAYERS(playerName, country, points, positions, basicprice) VALUES ('Aswin','INDIA',4,'BATSMAN',3);